### ISSUE TITLE
BUG: Textures not aligned

### ISSUE THREAD

**Issue by elmisto** [proof88/PRooFPS-dd#271]
Hi!

I've noticed that textures are not properly aligned to the geometry on the horizontal axis. Example:
![image](https://github.com/proof88/PRooFPS-dd/assets/3153605/71394012-9384-4be4-8259-9d0bf7b92fac)

Original texture:
![image](https://github.com/proof88/PRooFPS-dd/assets/3153605/1d252eb3-066d-44ff-a1d5-310530d611e9)

It's only visible when using non-tileable textures.

**Comment by elmisto** [comment]
Any update on this issue?

**Comment by elmisto** [comment]
Found the problem.

When exporting with gimp you have to disable writing color space information to the BMP file.
![image](https://github.com/proof88/PRooFPS-dd/assets/3153605/0de6d2fd-1290-4467-8324-3f8a58f50dc4)

**Comment by proof88** [comment]
Hello,

thank you for the detailed bugreport and the workaround for this issue.
I have informed the engine development team about this and they are tracking the issue in this ticket:
https://github.com/proof88/PGE/issues/13

Regards,
proof88
